- name: stop ddclient service
  systemd:
    name: ddclient
    state: stopped
  failed_when: false

- name: disable ddclient service
  systemd:
    name: ddclient
    enabled: no
    daemon_reload: yes
  failed_when: false

- name: uninstall the ddclient packages
  apt:
    name: ddclient
    state: absent

- name: delete ddclient config
  file:
    path: /etc/ddclient.conf
    state: absent