influxdb2_outputs:
  - url: "{{ vault_influxdb2_dmiller_url }}"
    token: "{{ vault_influxdb2_dmiller_token }}"
    organization: "{{ vault_influxdb2_dmiller_organization }}"
    bucket: "{{ vault_influxdb2_dmiller_metrics_bucket }}"
    namedrop:
      - syslog
  - url: "{{ vault_influxdb2_dmiller_url }}"
    token: "{{ vault_influxdb2_dmiller_token }}"
    organization: "{{ vault_influxdb2_dmiller_organization }}"
    bucket: "{{ vault_influxdb2_dmiller_logs_bucket }}"
    namepass:
      - syslog

nas1_cifs_share_host: "{{ vault_nas1_cifs_share_host }}"
nas1_cifs_share_username: "{{ vault_nas1_cifs_share_username }}"
nas1_cifs_share_password: "{{ vault_nas1_cifs_share_password }}"
