ansible_host: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64663833303030376132393838663935343137363534663461353164636161373866323438383263
  6562663539356636616233633731623831313661343633310a396538393166613538653030373363
  64613430663033306437613437623465613161303465656538306438643335623362633230356565
  3564663730386636330a386332613432346535326333643638663264326539393635376338346563
  64653163626132313038363837393937333661306339353332326665313965383438

authorized_keys:
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNxxAEcT71BAXlVhmi76gjI26BkXwjAgcLaPLIMI+i8 dmiller
    user: pi
    state: present
  - key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPUgzXYNTvTCcUHjzdXvy2LZA6YFZKrHrfsse3ipP2ldbhnmU/Io9I/lUligmdaCFktcxwgzZRYawWJI1IsUnZA= dmiller
    user: pi
    state: present
  - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChNryHWkasg7O7YLfLSffWjrP+e6eAt5olYIPgBCeqBgPHYK3sJkAo/UHuJ1SQA22qMQlHI/2m2chASZ7tbbkaBEkWlBlbAQpwleuJE0WBN8hJd49dJToW9d6q6hNwq9bmnlA/VTkzsLAqpSEANnO28WMhHI+Upn924L4lC4tVJQmSUPm8ENgU5RVW9EcSkfIBPrIdFW0zqxPEFzZXlaOqxmbOvgS4qWirjHe4PXC1Z8DeYlK9DSTM/KGX0pz8Jgz0shKwxDpdn/j36KP1jlygwrWmnDXuWuMuU44HjMZzA3A9XKuHqiROrv1K0A4M1t5DN/UbWSNQBhQOWdica2Qaek2+dUQ5m5bgYw7sSTW5Oz/jvWU71NdFhmN9eXCJukiN7UwznecnOHf0O/Si5fFf6iJzLjHELi1JKzVLvADyZTlaxmZB82MmveB99eArOUquaeO4rOHugmOVosW/Gg4wj1j19gFy0E+yVuP01tg999YF2ST8l6Z81w2xBrZYKKw+tgQlm/WbxkzRxnumTx7JH/AddFTZvTADQB11DRySmrWBKC4QCGo8+8SdwitHt6WzDZAuOqYPK+mtMtGY3TKGazRRUvCKVTALamJWjbZcizQGj3PqfVr8+wB/+TzsUU9vJPPo9skZrYHwom/3Wu1TlAAaYd8hTriqGK7gzm1CNw== dmiller
    user: pi
    state: present

additional_docker_users:
  - pi

lightdm_autologin_user: pi
lightdm_xorg_create_video_dummy: yes

sudoers:
  - user: pi
    passwordless: true

project_files:
  - src: "plaintext/{{ inventory_hostname }}/var/docker/mosquitto/config/mosquitto.conf"
    dest: /var/docker/mosquitto/config/mosquitto.conf
    owner: 1883
    group: 1883
    mode: '0640'
  - src: "vault/{{ inventory_hostname }}/var/docker/mosquitto/config/mosquitto.passwd"
    dest: /var/docker/mosquitto/config/mosquitto.passwd
    owner: 1883
    group: 1883
    mode: '0700'

raspberry_pi_wifi_country: US
raspberry_pi_video_group_users:
  - pi
raspberry_pi_swap_size_mb: 0
