- assert:
    that: openvpn_client_state in ('present', 'absent')
- assert:
    that: ansible_os_family == 'Debian'
- assert:
    that: ansible_service_mgr == 'systemd'

- include_tasks: "{{ openvpn_client_state }}.yml"
