- name: stop {{ ethminer_coin_service }} service
  systemd:
    name: "{{ ethminer_coin_service }}.service"
    state: stopped
  failed_when: false

- name: stop {{ ethminer_coin_service }} timer
  systemd:
    name: "{{ ethminer_coin_service }}.timer"
    state: stopped
  failed_when: false

- name: disable {{ ethminer_coin_service }} service
  systemd:
    name: "{{ ethminer_coin_service }}.service"
    enabled: no
    daemon_reload: yes
  failed_when: false

- name: disable {{ ethminer_coin_service }} timer
  systemd:
    name: "{{ ethminer_coin_service }}.timer"
    enabled: no
    daemon_reload: yes
  failed_when: false

- name: delete {{ ethminer_coin_service }} service
  file:
    path: /etc/systemd/system/{{ ethminer_coin_service }}.service
    state: absent

- name: delete {{ ethminer_coin_service }} timer
  file:
    path: /etc/systemd/system/{{ ethminer_coin_service }}.timer
    state: absent
