- name: create {{ ethminer_coin_service }} service
  template:
    src: ethminer.service.jinja2
    dest: /etc/systemd/system/{{ ethminer_coin_service }}.service
    owner: "{{ root_user|default('root') }}"
    group: "{{ root_group|default('root') }}"
    mode: 0644
  notify: restart ethminer

- name: create {{ ethminer_coin_service }} timer
  template:
    src: ethminer.timer.jinja2
    dest: /etc/systemd/system/{{ ethminer_coin_service }}.timer
    owner: "{{ root_user|default('root') }}"
    group: "{{ root_group|default('root') }}"
    mode: 0644
  notify: restart ethminer

- name: disable {{ ethminer_coin_service }} service to defer to timer
  systemd:
    name: "{{ ethminer_coin_service }}.service"
    enabled: no
    daemon_reload: yes

- name: enable {{ ethminer_coin_service }} timer
  systemd:
    name: "{{ ethminer_coin_service }}.timer"
    enabled: yes
    daemon_reload: yes

- meta: flush_handlers

- name: start {{ ethminer_coin_service }} timer
  systemd:
    name: "{{ ethminer_coin_service }}.timer"
    state: started
