- name: set sysctl params
  when: sysctl_params
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ sysctl_file }}"
    sysctl_set: yes
    reload: no
  with_items: "{{ sysctl_params }}"
  notify: reload sysctl

- name: delete sysctl params
  when: not sysctl_params
  file:
    path: "{{ sysctl_file }}"
    state: absent
  notify: reload sysctl
