ansible_surrogate_user: ansible
vault_dir_name: vault

pip_default_index_url: https://pypi.python.org/simple
pip_version_spec:
setuptools_version_spec:
virtualenv_version_spec:

pki_tls_ca_bundle: /etc/ssl/certs/ca-certificates.crt
pki_tls_dir: /etc/ssl
pki_tls_private_dir: /etc/ssl/private
pki_tls_private_group: ssl-cert

influxdb_host: "{{ vault_influxdb_host }}"
influxdb_username: "{{ vault_influxdb_username }}"
influxdb_password: "{{ vault_influxdb_password }}"
influxdb_scheme: https
influxdb_port: 443
influxdb_url: "{{ influxdb_scheme }}://{{ influxdb_host }}:{{ influxdb_port }}"
influxdb_database_name: telegraf

postfix_relayhost: smtp-relay.gmail.com
postfix_relayhost_port: 587
postfix_sasl_user: "{{ vault_postfix_sasl_user }}"
postfix_sasl_password: "{{ vault_postfix_sasl_password }}"

vnc_password: "{{ vault_vnc_password }}"

alert_email_address: "{{ vault_alert_email_address }}"

nicehash_rig_id: "{{ ansible_hostname }}"
nicehash_mining_address: "{{ vault_nicehash_mining_address }}"

authorized_keys: []
sudoers: []
