- assert:
    that: systemd_status_mail_state in ('present', 'absent')
- assert:
    that: ansible_service_mgr == 'systemd'

- name: create status mail script
  template:
    src: systemd-status-mail.jinja2
    dest: "{{ systemd_status_mail_script }}"
    owner: root
    group: root
    mode: 0755
  when: systemd_status_mail_state == 'present'

- name: create status mail service
  template:
    src: status-mail@.service.jinja2
    dest: /etc/systemd/system/{{ systemd_status_mail_service }}@.service
    owner: root
    group: root
    mode: 0644
  when: systemd_status_mail_state == 'present'

- name: delete status mail script and service
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/{{ systemd_status_mail_service }}@.service
    - "{{ systemd_status_mail_script }}"
  when: systemd_status_mail_state == 'absent'
