- name: stop {{ ethminer_coin_service }} service
  systemd:
    name: "{{ ethminer_coin_service }}"
    state: stopped
  failed_when: false

- name: disable {{ ethminer_coin_service }} service
  systemd:
    name: "{{ ethminer_coin_service }}"
    enabled: no
    daemon_reload: yes
  failed_when: false

- name: delete {{ ethminer_coin_service }} service
  file:
    path: /etc/systemd/system/{{ ethminer_coin_service }}.service
    state: absent
