- assert:
    that: lightdm_state in ('present',)
- assert:
    that: ansible_os_family == 'Debian'
- assert:
    that: ansible_service_mgr == 'systemd'

- name: install lightdm
  apt:
    name:
      - lightdm
      - libglib2.0-bin
    state: latest
  notify: restart lightdm

- name: write lightdm configuration
  template:
    src: lightdm.conf.j2
    dest: '{{ lightdm_conf_directory }}/{{ lightdm_overide_filename }}'
    owner: root
    group: root
    mode: 0644
  register: lightdm_config

- name: apply glib schemas changes
  command: '/usr/bin/glib-compile-schemas {{ lightdm_glib_schemas_directory }}'
  when: lightdm_config.changed
  notify: restart lightdm
