- assert:
    that: tplink_plug_stats_state in ('present', 'absent')

- when: tplink_plug_stats_state == 'present'
  block:
    - name: install python dependencies
      pip:
        virtualenv: "{{ tplink_plug_stats_virtualenv_path }}"
        name:
          - click
          - python-kasa
        extra_args: --pre --upgrade-strategy only-if-needed
        state: latest
      environment:
        SETUPTOOLS_USE_DISTUTILS: stdlib

    - name: create tplink-plug-stats script dir
      file:
        path: "{{ tplink_plug_stats_script_path|dirname }}"
        owner: "{{ root_user|default('root') }}"
        group: "{{ root_group|default('root') }}"
        mode: 0755
        state: directory

    - name: copy tplink-plug-stats script
      template:
        src: tplink-plug-stats.jinja2
        dest: "{{ tplink_plug_stats_script_path }}"
        owner: "{{ root_user|default('root') }}"
        group: "{{ root_group|default('root') }}"
        mode: 0755

- include_role:
    name: generic/telegraf/plugin
  vars:
    telegraf_plugin_conf_src: telegraf.conf.jinja2
    telegraf_plugin_conf: tplink-plug-stats.conf
    telegraf_plugin_state: "{{ 'present' if tplink_plug_stats_state == 'present' and tplink_plug_stats_ip_addresses|length > 0 else 'absent' }}"

- name: delete tplink-plug-stats script
  file:
    path: "{{ tplink_plug_stats_dir }}"
    state: absent
  when: tplink_plug_stats_state == 'absent'
