- assert:
    that: ethminer_exe_state in ('present', 'absent')
- assert:
    that: ansible_os_family == 'Debian'
- assert:
    that: ansible_service_mgr == 'systemd'

- include_tasks: "{{ ethminer_exe_state }}.yml"
