ansible_host: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61653761623965656666653866346532643933313466303235376434383831336331353363386137
  3938323662386166653131313937383466303061383433300a376364336636633935306165643038
  39653564373262636662653037663766303439663937346363326535383833656563313930666466
  3565393466663866380a393431376532663161663634363462656337363931346531326237346465
  63613834383635663732626331323565383332643064393933353761663563393134

authorized_keys:
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNxxAEcT71BAXlVhmi76gjI26BkXwjAgcLaPLIMI+i8 dmiller
    user: pi
    state: present
  - key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPUgzXYNTvTCcUHjzdXvy2LZA6YFZKrHrfsse3ipP2ldbhnmU/Io9I/lUligmdaCFktcxwgzZRYawWJI1IsUnZA= dmiller
    user: pi
    state: present
  - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChNryHWkasg7O7YLfLSffWjrP+e6eAt5olYIPgBCeqBgPHYK3sJkAo/UHuJ1SQA22qMQlHI/2m2chASZ7tbbkaBEkWlBlbAQpwleuJE0WBN8hJd49dJToW9d6q6hNwq9bmnlA/VTkzsLAqpSEANnO28WMhHI+Upn924L4lC4tVJQmSUPm8ENgU5RVW9EcSkfIBPrIdFW0zqxPEFzZXlaOqxmbOvgS4qWirjHe4PXC1Z8DeYlK9DSTM/KGX0pz8Jgz0shKwxDpdn/j36KP1jlygwrWmnDXuWuMuU44HjMZzA3A9XKuHqiROrv1K0A4M1t5DN/UbWSNQBhQOWdica2Qaek2+dUQ5m5bgYw7sSTW5Oz/jvWU71NdFhmN9eXCJukiN7UwznecnOHf0O/Si5fFf6iJzLjHELi1JKzVLvADyZTlaxmZB82MmveB99eArOUquaeO4rOHugmOVosW/Gg4wj1j19gFy0E+yVuP01tg999YF2ST8l6Z81w2xBrZYKKw+tgQlm/WbxkzRxnumTx7JH/AddFTZvTADQB11DRySmrWBKC4QCGo8+8SdwitHt6WzDZAuOqYPK+mtMtGY3TKGazRRUvCKVTALamJWjbZcizQGj3PqfVr8+wB/+TzsUU9vJPPo9skZrYHwom/3Wu1TlAAaYd8hTriqGK7gzm1CNw== dmiller
    user: pi
    state: present

additional_docker_users:
  - pi
docker_compose_definition:
  version: '3'
  networks:
    apps:
      driver: bridge
  volumes:
    homebridge:
  services:
    portainer-agent:
      container_name: portainer-agent
      image: portainer/agent:latest
      restart: unless-stopped
      networks:
        - apps
      ports:
        - "9001:9001"
      volumes:
        - /var/lib/docker/volumes:/var/lib/docker/volumes
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        TZ: America/Chicago
    homebridge:
      container_name: homebridge
      restart: unless-stopped
      image: homebridge/homebridge:latest
      network_mode: host
      logging:
        driver: json-file
        options:
          max-size: "10mb"
          max-file: "1"
      volumes:
        - homebridge:/homebridge
      environment:
        ENABLE_AVAHI: 1
        HOMEBRIDGE_CONFIG_UI: 1
        HOMEBRIDGE_CONFIG_UI_PORT: 8581
        PGID: 1000
        PUID: 1000
        TZ: America/Chicago

lightdm_autologin_user: pi
lightdm_xorg_create_video_dummy: yes

sudoers:
  - user: pi
    passwordless: true

tailscale_args: --advertise-routes=192.168.1.10/31 # Control4 controller & DS2

raspberry_pi_poe_hat: true
raspberry_pi_wifi_country: US
raspberry_pi_video_group_users:
  - pi
raspberry_pi_boot_config_options:
  - option: gpu_mem
    value: 160
