ddclient_state: present
ddclient_daemon: 120
ddclient_syslog: yes
ddclient_ssl: yes
ddclient_protocol: dyndns2
ddclient_server: domains.google.com
ddclient_use: web, web=checkip.dyndns.com, web-skip='IP Address'

# must set:
# ddclient_login:
# ddclient_password:
# ddclient_subdomain:
