nut_state: present
nut_max_retry: 3
nut_mode: netserver

nut_user_master_name: monuser
nut_user_slave_name: monuserslave

nut_ups_devices: []
nut_ups_monitors: []
nut_ups_listen: |
  LISTEN 127.0.0.1 3493
  LISTEN {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} 3493
  LISTEN ::1 3493

# must set:
# nut_user_master_password
# nut_user_slave_password
