- assert:
    that: python_state == 'present'
    quiet: yes

- name: install pip3
  apt:
    name: python3-pip
    state: latest

- name: check if pip3 needs upgrade before using disable-pip-version-check flag
  command: pip3 --version
  register: pip_no_disable_pip_version_check
  changed_when: (pip_no_disable_pip_version_check.stdout | regex_replace('^pip ([^ ]+).*$', '\\1')) is version_compare('6.0', '<')

- name: check if pip3 needs break-system-packages flag
  command: pip3 install --help
  register: pip_break_system_packages_check
  changed_when: false

- name: set pip_break_system_packages var
  set_fact:
    pip_break_system_packages: "{{ ' --break-system-packages ' in pip_break_system_packages_check.stdout }}"

- name: upgrade/downgrade setuptools and pip
  pip:
    name:
      - setuptools{{ setuptools_version_spec }}
      - pip{{ pip_version_spec }}
    executable: pip3
    extra_args: "{{ '--break-system-packages' if pip_break_system_packages else '' }} {{ '' if pip_no_disable_pip_version_check is changed else '--disable-pip-version-check' }}"
    state: latest

- name: install/upgrade virtualenv
  pip:
    name: virtualenv{{ virtualenv_version_spec }}
    executable: pip3
    extra_args: "{{ '--break-system-packages' if pip_break_system_packages else '' }} --disable-pip-version-check"
    state: latest
