- name: stop {{ msi_rgb_service }} service
  systemd:
    name: "{{ msi_rgb_service }}"
    state: stopped
  failed_when: false

- name: disable {{ msi_rgb_service }} service
  systemd:
    name: "{{ msi_rgb_service }}"
    enabled: no
    daemon_reload: yes
  failed_when: false

- name: delete {{ msi_rgb_service }} service
  file:
    path: /etc/systemd/system/{{ msi_rgb_service }}.service
    state: absent

- name: delete msi-rgb install directory
  file:
    dest: "{{ msi_rgb_install_dir }}"
    state: absent
